apiVersion: v1
kind: ConfigMap
metadata:
  name: relatorio-config
data:
  DatabaseConnection__Host: "__DB_HOST__"
  DatabaseConnection__Port: "5432"
  DatabaseConnection__DatabaseName: "__DB_NAME__"
  DatabaseConnection__User: "__DB_MASTER_USERNAME__"
  
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  
  ApiCredentials__ClientId: "admin"

  AWS__Region: "us-east-1"

  NEW_RELIC_APP_NAME: "RelatorioService"
  NEW_RELIC_APPLICATION_LOGGING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_CONTEXT_DATA_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_METRICS_ENABLED: "true"
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
  NEW_RELIC_LOG_LEVEL: "info"
  
  CORECLR_ENABLE_PROFILING: "1"
  CORECLR_PROFILER: "{36032161-FFC0-4B61-B559-F6C5D41BAE5A}"
  CORECLR_PROFILER_PATH: "/usr/local/newrelic-dotnet-agent/libNewRelicProfiler.so"
  CORECLR_NEWRELIC_HOME: "/usr/local/newrelic-dotnet-agent"
