apiVersion: v1
kind: Secret
metadata:
  name: relatorio-secret
type: Opaque
stringData:
  DatabaseConnection__Password: "__DB_MASTER_PASSWORD__"
  ApiCredentials__ClientSecret: "admin"
  AWS__AccessKeyId: "__AWS_ACCESS_KEY_ID__"
  AWS__SecretAccessKey: "__AWS_SECRET_ACCESS_KEY__"
  AWS_ACCESS_KEY_ID: "__AWS_ACCESS_KEY_ID__"
  AWS_SECRET_ACCESS_KEY: "__AWS_SECRET_ACCESS_KEY__"
  NEW_RELIC_LICENSE_KEY: "__NEW_RELIC_LICENSE_KEY__"
