// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415001357_AdicionarDataUltimaTentativa")]
    partial class AdicionarDataUltimaTentativa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.ResultadoDiagrama.Aggregates.ResultadoDiagrama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnaliseDiagramaId")
                        .HasColumnType("uuid")
                        .HasColumnName("analise_diagrama_id");

                    b.Property<string>("AnaliseResultado")
                        .HasColumnType("jsonb")
                        .HasColumnName("analise_resultado");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTimeOffset>("DataUltimaTentativa")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ultima_tentativa");

                    b.Property<string>("Erros")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("erros");

                    b.Property<string>("Relatorios")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("relatorios");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_analise");

                    b.HasKey("Id");

                    b.HasIndex("AnaliseDiagramaId")
                        .IsUnique();

                    b.ToTable("resultado_diagramas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
